"""categories table

Revision ID: ae51ec2bb41b
Revises: 
Create Date: 2022-06-26 15:46:55.267540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae51ec2bb41b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_en', sa.String(length=64), nullable=True),
    sa.Column('category_ru', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_category_en'), 'categories', ['category_en'], unique=True)
    op.create_index(op.f('ix_categories_category_ru'), 'categories', ['category_ru'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_categories_category_ru'), table_name='categories')
    op.drop_index(op.f('ix_categories_category_en'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
